name: Test
on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022
          - windows-2019
          - windows-2016
          - macOS-12
          - macOS-11
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Init gradle project
        run: ./gradlew clean --scan

      - name: Build all
        run: ./gradlew assemble --scan

      - name: SkiaExampleKtTest
        run: ./gradlew test --tests "xyz.cssxsh.skia.ExampleKtTest" --scan --info

      - name: GifEncoderTest
        run: ./gradlew test --tests "xyz.cssxsh.gif.EncoderTest" --scan --info